### PR TITLE
feat: `HasIslands` supports nested components

### PR DESCRIPTION
**Pull request by bruceharrison1984**
This makes a change to the Islands scanning code so that it walks the dependency tree. The current implementation only allows for islands to work if they are directly within the Route. This change allows Islands to be anywhere in the hierarchy.

This PR is more of a working session to try and get this sorted out, because the current implementation is extremely limited and negatively impacts the way users can structure their components. The other alternative is to just always ship the client libraries, but that seems to run counter to why Islands was implemented in the first place.

Current shortfalls:
- Slightly increases transformation time
- Only scans for `tsx` files

This works was based on conversations from #46

### CODE REVIEW

**Comment by yusukebe** [comment]
Hey @bruceharrison1984 !

I have made changes to 7099fba2bd3c992c2496fcf30fc3d2d643db1cee. Anyway, this PR must be completed. What do you think my chage?

**Comment by bruceharrison1984** [comment]
@yusukebe Is this also working with alias imports? That was one issue with what currently exists. I *think* that by using `this.resolve`, we should be able to get that working as well.

**Comment by yusukebe** [comment]
@bruceharrison1984 

>  Is this also working with alias imports?

Yeah. I added tests for alias importing. 86129369d566523ac2e1ef93d07592517b519209. It seems to be working! Can you see this again?

**Comment by yusukebe** [comment]
After merge this, we have to resolve this matter:  #105

**Comment by bruceharrison1984** [comment]
@yusukebe LGTM

Was the only piece I was missing adding the alias to the `vite.config.js`? I feel like a fool 😄

**Comment by yusukebe** [comment]
@bruceharrison1984 Thanks!

Land it!

**Pull request merged**
