### PR TITLE
feat: Add sitemap plugin

### LINKED ISSUE #216: Proposal: Vite plugin for sitemap.xml generation in SSR mode for HonoX
### What is the feature you are proposing?

I've developed a Vite plugin that generates a sitemap.xml file in SSR mode, with default arguments tailored for HonoX projects. While this functionality isn't directly related to HonoX's core features, I believe it could be a valuable addition to the ecosystem.

I'd like to propose integrating this plugin into the HonoX project. Here are some points for consideration:

1. The plugin simplifies sitemap generation for HonoX users, enhancing SEO capabilities.
2. It's designed with HonoX in mind, making it seamless for existing projects.
3. Including it in the official project could provide better maintenance and support.

Alternatively, if you feel this plugin would be better suited as a separate package, I'm open to releasing it independently on npm under my personal responsibility.

I'd appreciate your thoughts on this proposal. Would you be interested in incorporating this plugin into HonoX, or do you recommend releasing it as a standalone package?

Thank you for your time and consideration.

https://github.com/kbkn3/gensya-akuyaku-source/blob/develop/app/sitemap.ts

### PR DESCRIPTION
**Pull request by kbkn3**
Close #216

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @kbkn3 

Thank you for the awesome PR!

I've tried it with `x-basic` template created by `create-hono` command. But the build will fail:

CleanShot 2024-08-30 at 15 23 13@2x

The build command is the following:

```bash
vite build --mode client && vite build
```

Can you take a look?

And if you can, please describe this feature in `README.md`.

After that, I'll review the details.

**Comment by kbkn3** [comment]
Hi @yusukebe 
Thank you for checking my PR.

I fixed the error when I had never done a build and the `dist` directory did not exist.
I have successfully `build` with `x-basic` template in my environment.

I have also added the README, so please check it out!

**Comment by yusukebe** [comment]
@kbkn3 

Thank you for handling them.

There is a big problem with this plugin. If it has the following route on `app/routes/about/index.tsx`, this is not supported well:

```tsx
import { Hono } from 'hono'

const app = new Hono()

app.get('/me', (c) => {
  return c.render(<h1>About me!</h1>)
})

export default app
```

We have to consider this patter. The `inspectRoutes` in `hono/dev` maybe help you.

**Comment by kbkn3** [comment]
@yusukebe 

I had forgotten that notation existed...
Sorry for neglecting to check the test. I will make sure to check it.

It seems that `inspectRoutes(app)` cannot be used in `vite.config.ts` or `plugin`.
It's probably because I'm using `import.meta.glob` inside `app`.

I think I'll replace the process that makes file-based routing in `honox` with a node-based one and implement it inside the sitemap plugin.

-----
I get the following error when using `inspectRoutes(app)`
```
error during build:
[vite-plugin-hono-sitemap] (intermediate value).glob is not a function
```

**Comment by kbkn3** [comment]
@yusukebe 

- I tried building `/app/server.ts` and doing a dynamic import, but the dynamic import itself doesn't seem to work!
 - I tried simply passing the result of inspectRoute(app) as a plugin argument, but failed because import.meta.glob is not available in the Node.js environment
 - I thought of a way to find a match for `.get('/**')` in the contents of the file, but decided against it because it would not work if the proprietary method had a similar notation.

 I am considering CLOSE because I have thought about it a lot but can't think of a way to achieve the current status.
 Any ideas?

**Comment by yusukebe** [comment]
Hi @kbkn3 

I think we can make a hook of [the SSG Helper](https://hono.dev/docs/helpers/ssg) for creating Sitemap. I'm not sure it's correct but it may be made as `AfterGenerateHook`: 

https://github.com/honojs/hono/blob/f9a23a9992979fed79b0703ab8b3a3ce49f7175f/src/helper/ssg/ssg.ts#L98

And we have [@hono/vite-ssg](https://github.com/honojs/vite-plugins/tree/main/packages/ssg). This plugin can support `import.meta.glob`.

We have to consider the API design, but we may make the feature for Sitemap with them.

**Comment by yusukebe** [comment]
And, if we follow the method, the hook for creating a Sitemap is not only for HonoX. It can be used in the apps using SSG Helper.

**Comment by kbkn3** [comment]
@yusukebe 
Seems like a good idea. Thank you.

I came up with a way to output the sitemap as a normal route, so I implemented it as a function and pushed it.
It seems like it would be enough for each developer to implement...

However, it seems smarter to implement it as a hono function using @hono/vite-ssg.
I will consider implementing it using @hono/vite-ssg and hooks.

**Comment by yusukebe** [comment]
@kbkn3 

Okay! Thank you very much!

**Pull request closed without merging**
