### PR TITLE
fix: add "key" attribute to suppress react "key" warnings

### PR DESCRIPTION
**Pull request by usualoma**
### b953beb5735fd522fe345ce7ef1a402dbe16360a

As @yusukebe pointed out in https://github.com/honojs/honox/issues/233#issuecomment-2475227165, `template` elements are written out as arrays, but without the key attribute, which caused a warning, has been fixed.

### be543f3b49000480b7fad144439e6c11d7552b56

There was no key attribute left in the content of the template element, which was exported by SSR, but when the element was restored by creatingElement on the client side, a warning was displayed due to the absence of the key attribute.

It may seem strange to add the key attribute with a sequential number, but these elements are not overwritten after rendering by the client, so there is no problem if the warning is avoided by adding a sequential number.

### CODE REVIEW

**Comment by usualoma** [comment]
I am investigating the failure of the test...

**Comment by usualoma** [comment]
### bcb8fdc

We are using `jsx` directly for the performance, but with this change, we needed to remove the “key" from the props as follows, so we should stop using `jsx` directly and started using `createElement`.
https://github.com/honojs/hono/blob/44a50bdf55850ead9d36caf31d4b0a0b2586f08b/src/jsx/dom/index.ts#L52-L55

**Comment by usualoma** [comment]
@yusukebe 
Would you please review?

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Hi @usualoma 

These commits make sense. Looks good. I'll merge and release a new version. Thank you!

**Pull request merged**
